language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
  jwt:
    secure: SvXLi0UK09YJDHq6ovThFX+3MErqrK3caJQa2FBuz5HQ1BFrY2nFATqNeEE4e5o3ZKy6ebLCvw6plCE7x3hnSYMLLJGYeNi2h0UPqZ+xfSs7EFvuHmgGKFRVDmeZ4xVnmN+kDhcjjfaVpyVaDmwaPuxzDE5NV2gJI/O5xQhLwncyhSl0ctBxtpQYY9MxD/oexVDbLCKRMf2yCgvVax3nYd0Tr99sDSTdQ/6klbi55p/Xs91taB9OdETK7oCug5FWIaTGrC85zY4KdmNx8XdkJk/p7kCCNNmalEiwSw3DPBBQgAYENCADo2b5laMPQHZ2HlFqFlM7/ca0t8jF1xTr2yKEV1z65TJLyY/utCai1OSt3ItNlFdi/vMYTnWZSIsi+hfW2jHdYGP0LxBOmhdk48bp2AC1SD7Hgg0z2KIOtKlIG/YfODzzolPeN1F4OYYmCaUIkeiGnHOtLWQJHF11ZKig4jYLe5+cDH3Q2pV7UpA6aTB4Q7qccBbSqEV4ie6MeJH78ZlId95OVeANXGrg0yYUSx9SAzvHvRQzEAMcPIiqJTtr5oejOtcM84sMxG0IUU9XntETc3myb4VBejB8aDYjau8Hg8RMK1zB1zegGNqd3+iPr3IN/s29v74yhjNEho0wdzhex1AynUgp2LN60EDhjFN+hAnMrNF2GllEd+Y=
before_install:
  - nvm install 5
install:
  - npm i
before_script:
  
script: travis_wait gulp test:saucelabs
env:
  global:
  - secure: nGC6fcKHhzU4QPiA+6ozOqDPZ+x6vN5di7JlwK/HraWxN2o1CvhWOsVjYaSma/qjBQtnxp75bTyPRZhUKA+rQJftU+DO4goi3q7Rp3zcbFjTEhZ6OLzgSyMgSW86WH4waoUN8JG77WWkswj8nHrkzXoQZOQL6QHrqCKuVL6TktI=
  - secure: ktay4HmZr28wffIdxPyrFEbR2WezQHg5U2xAaq5jEqfihjqdVH2hGHvfDeASPELmZQwFPch0SO2OPwdiYFvCQDCxd7R9WozecOSWjNOdjyDR8Pn2NCL/N9fQ48alEi+BjgM5ei0T9U9xZnTbonrKch1kaipmJdAE4PsOdLDdoCg=
